// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3707.Creedence.commands.autonomous;

import org.usfirst.frc3707.Creedence.commands.hatch.closeClawCommand;
import org.usfirst.frc3707.Creedence.commands.hatch.thrustBackwardCommand;
import org.usfirst.frc3707.Creedence.commands.hatch.thrustForwardCommand;
import org.usfirst.frc3707.Creedence.commands.lift.hatchToBotCommand;
import org.usfirst.frc3707.Creedence.commands.autonomous.*;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AutoGrabSequence extends CommandGroup {

    
    public AutoGrabSequence() {


        addSequential(new thrustForwardCommand());
        addSequential(new closeClawCommand());
        addParallel(new autoPStationCommand(), 10);
        addSequential(new AutoGrabCommand(), 10);
        
        //the blank command is a timer, the code reaches it and waits for the timeout that you set
        //addSequential(new blankCommand(), .2 );
        addSequential(new conditionalThrustBackward());
    }
}
