// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3707.Creedence.commands.autonomous;

import org.usfirst.frc3707.Creedence.commands.hatch.closeClaw;
import org.usfirst.frc3707.Creedence.commands.hatch.thrustForward;
import org.usfirst.frc3707.Creedence.commands.hatch.timedThrustBackward;
import org.usfirst.frc3707.Creedence.commands.lift.hatchToPStation;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AutoGrabSequence extends CommandGroup {

    
    public AutoGrabSequence() {

        addSequential(new thrustForward());
        addSequential(new closeClaw());
        // addSequential(new hatchToPStation());
        // addSequential(new hatchToPStation());
        // addSequential(new hatchToPStation());
        // addSequential(new hatchToPStation());
        // addSequential(new hatchToPStation());
        // addSequential(new hatchToPStation());
        //timer right here
        addSequential(new AutoGrabCommand());
        addSequential(new timedThrustBackward());
    }
}
