// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3707.Creedence.commands.autonomous;

import org.usfirst.frc3707.Creedence.commands.hatch.closeClawCommand;
import org.usfirst.frc3707.Creedence.commands.hatch.thrustForwardCommand;
import org.usfirst.frc3707.Creedence.commands.lift.hatchToPStationCommand;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AutoGrabSequence extends CommandGroup {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AutoGrabSequence() {

        addSequential(new thrustForwardCommand());
        addSequential(new closeClawCommand());
        addSequential(new hatchToPStationCommand());
        addSequential(new hatchToPStationCommand());
        addSequential(new hatchToPStationCommand());
        addSequential(new hatchToPStationCommand());
        addSequential(new hatchToPStationCommand());
        addSequential(new hatchToPStationCommand());
        //timer right here
        //addSequential(new closeClaw(), 4000); example of timers for sequentials
        addSequential(new AutoGrabCommand());
        //addSequential(new timedThrustBackward());




        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
}
