// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3707.Creedence.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class commandGroup extends CommandGroup {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public commandGroup() {

        addSequential(new thrustBackward());
        addSequential(new closeClaw());
        addSequential(new hatchToPStation());
        addSequential(new hatchToPStation());
        addSequential(new hatchToPStation());
        addSequential(new hatchToPStation());
        addSequential(new hatchToPStation());
        addSequential(new hatchToPStation());
        // addSequential(new lineUpToTape());
        addSequential(new thrustForward());
        //timer right here
        addSequential(new openClawTimed());



        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
}
