// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3707.Creedence.commands;

import org.usfirst.frc3707.Creedence.Robot;
import org.usfirst.frc3707.Creedence.subsystems.DriveTrain;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class Drive extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public Drive() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    double prank = .01;

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        Robot.driveTrain.enable();
    }

    //Lidar lidarCrab = new Lidar(new DigitalInput(10));

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        if (Robot.oi.joystick1.getRawButton(5))
        {
            Robot.driveTrain.drive(-Robot.driveTrain.getError(), -Robot.oi.joystick1.getRawAxis(1), -Robot.driveTrain.getSpinValue(), Robot.oi.joystick1.getRawButton(3), Robot.oi.joystick1.getRawButton(6), Robot.oi.joystick1.getRawButton(3));
        }
        else
        {
            Robot.driveTrain.drive(-Robot.oi.joystick1.getRawAxis(0), -Robot.oi.joystick1.getRawAxis(1), -Robot.oi.joystick1.getRawAxis(4), Robot.oi.joystick1.getRawButton(3), Robot.oi.joystick1.getRawButton(6), Robot.oi.joystick1.getRawButton(3));
        }
        
       // Robot.driveTrain.drive(Robot.oi.joystick1.getRawAxis(4), Robot.oi.joystick1.getRawAxis(1), Robot.oi.joystick1.getRawAxis(0), Robot.oi.joystick1.getRawButton(3), Robot.oi.joystick1.getRawButton(2));
    }
    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {

        
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
