// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3707.Creedence.subsystems;

import org.usfirst.frc3707.Creedence.Robot;
import org.usfirst.frc3707.Creedence.Configuration.Constants;
import org.usfirst.frc3707.Creedence.commands.lift.liftUpAndDownCommand;
import org.usfirst.frc3707.Creedence.lidar.Lidar;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.PWMVictorSPX;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class LiftSubsystem extends Subsystem {

    private PWMVictorSPX elevator = new PWMVictorSPX(Constants.Elevator);
    public Lidar lidarCrab = new Lidar(new DigitalInput(Constants.lidar1));
    //public PWInput lidarSimple = new PWInput(new DigitalInput(Constants.lidar1));
    public PIDController liftController = new PIDController( 0.2, 0.0, 0.0, lidarCrab, elevator);
    

    //solinoid

    public LiftSubsystem() {
        liftController.setAbsoluteTolerance(0.5);
        //SmartDashboard.putNumber("Lift Height Value", 40);

        
    }

    @Override
    public void initDefaultCommand() {
        setDefaultCommand(new liftUpAndDownCommand());
    }

    /**
     * This method operates the teleop control of the game piece mechanism
     */
    public void liftUpAndDown() { 
        if ((Robot.oi.operatorController.getLeftStickYValue() > .3 || Robot.oi.operatorController.getLeftStickYValue() < -.3)) {
            elevator.set(Robot.oi.operatorController.getLeftStickYValue());
        } else {
            holdLift();
        }
    }

    public void liftUp() {
        elevator.set(-1);
    }

    public void liftDown() {
        elevator.set(1);
    }

    public void holdLift() {
        elevator.set(0.05);
    }

    public void liftUpOrDown(double power) {
        elevator.set(power);
    }

    public double getTargetHeight() {
        return SmartDashboard.getNumber("Lift Height Value", 40);
    }

    public double getLiftHeight() {
        return lidarCrab.getDistance();
    }


    @Override
    public void periodic() {
        SmartDashboard.putNumber("lidar #", lidarCrab.getDistance());
    }

}
